### ISSUE TITLE
[svlogd] / localtime timestamps?

### ISSUE THREAD

**Issue by riddicc** [void-linux/runit#24]
Hi!

Since I do not like UTC time (due to the minutes that are not all the same... [details...](https://www.reddit.com/r/voidlinux/comments/znlw6g/timezone_without_funny_minutesdays/)), I made myself a TAI time zoneinfo file, so that my box is not so affected by those funny minutes... I have true SI seconds (not like Google's smeared time...).

svlogd is somehow a step back, because it uses UTC timestamps or no (human readable) timestamps...

Since the runit dev team is not fond of my idea, they suggested, that it would be u, who i ask, to add the attached patch (after thorough cross checking... i didn't even try to compile it... *blush*)...

Thx.

Bye.

[ltime.patch.txt](https://github.com/void-linux/runit/files/11177753/ltime.patch.txt)

**Comment by classabbyamp** [comment]
i'm not sure what the point of this is. svlogd can already print tai (`svlogd -t`), and your changes to `fmt_ptime2()` don't change any functionality (the two sides of the `if` block are the same).

**Comment by riddicc** [comment]
@classabbyamp oh... thx... in the first case it should be _localtime_ instead of _gmtime_...
and the TAI of svlogd is not human readable...

**Comment by riddicc** [comment]
i replaced svlogd/nanoklog/socklog by my own "creation"...
