### ISSUE TITLE
Changing the coreutils to Busybox, Toybox, Sbase+Ubase results in error.

### ISSUE THREAD

**Issue by xplshn** [void-linux/runit#29]
The Runit init scripts(/etc/runit/1, 2, 3) fail after a reboot after changing the coreutils for more POSIX ones. Examples of why is are using swapon(1) -a and halt -B. Those are not the only ones, I just don't remember more right now. This would be a huge milestone for making Void Linux embedded friendly, though I know this system does not cater to the embedded Linux community, I'd be very grateful if any core Void developer cared. 

https://github.com/xplshn/AltSys contains a janky script that setups toybox+ubase+sbase(in that order) at /opt/ and changes the PATH variable in /etc/profile so that it works without breaking /etc/runit(unless you uninstall the coreutils).

**Comment by ahesford** [comment]
This isn't even the proper repository to address issues with the core-services scripts. Nevertheless, the core services target the standard tooling in Void. If you're going to replace that tooling with custom alternatives, you should expect to rewrite the services that depend on them. Furthermore, I don't thing `swapon` or `halt` interfaces are like this are governed by POSIX, and we don't target strict POSIX compliance either way.

**Comment by sgn** [comment]
- `swapon` and `halt` ain't governed by POSIX
- We take `swapon` from `util-linux`, but every proper `swapon` (including BusyBox's) have `swapon -a`
- Those scripts come from https://github.com/void-linux/void-runit/ which includes its own version of `halt`. So, it should work with that very version of `halt`.
- Anything else?

**Comment by xplshn** [comment]
Toybox's implementation of swapon does not have the -a flag, and ubase's does not receive UUID= arguments. Thanks for pointing me to the right repo anyways.
