### ISSUE TITLE
Should we rebase?

### ISSUE THREAD

**Issue by ericonr** [void-linux/runit#5]
https://github.com/sgn/orig-runit is a clone of the repo here -> https://www.mail-archive.com/supervision@list.skarnet.org/msg01353.html

Should we move to it or keep the current version that's only the releases?

Another option is making a separate branch with it for historical purposes

**Comment by sgn** [comment]
Either is fine to me. 62 vs 664 commits doesn't difference much to me.
The biggest issue with the original repository is the tarball in repository.

**Comment by CameronNemo** [comment]
Tarballs in repo are not a huge issue. Run git filter-branch and strip them out.

**Comment by ericonr** [comment]
Solved.
